version: 2

jobs:
 test_exec:
   docker:
     - image: maven:3.3-jdk-8
   steps:
     - checkout

     - run:
         name: Run test via maven
         command: mvn -Dtest=Runner test

nightly:
  triggers:
    - schedule:
        cron: "18 23 * * *"
        filters:
          branches:
            only:
              - AT-HomePage_Filters 