version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: convert to html
          command: |
            jupyter-nbconvert --execute./Domashka2.ipynb
      - path: ./Domashka2.html