  
version: 2.1

orbs:
  win: circleci/windows@2.3.0
jobs:
  build:
    executor: win/default
    steps:
    - checkout
    - run: jupyter nbconvert Domashka2.ipynb
    - store_artifacts:
        path: Domashka2.html
    - destination: Domashka2.html